[uwsgi]
strict
master
die-on-term
need-app
auto-procname
enable-threads
thunder-lock
disable-write-exception

chdir = /opt/healthchecks
module = hc.wsgi:application

harakiri = 30
buffer-size = 32768
post-buffering = 16192

; Workaround for https://github.com/unbit/uwsgi/issues/2299
max-fd = 10000
